package aplicacion.modelo.dominio;
// Generated 10-jun-2019 1:24:23 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modopago generated by hbm2java
 */
public class Modopago  implements java.io.Serializable {


     private Integer idmodoPago;
     private String descripcion;
     private Integer cuotas;
     private Double interes;
     private Set facturas = new HashSet(0);

    public Modopago() {
    }

	
    public Modopago(Integer idmodoPago) {
        this.idmodoPago = idmodoPago;
    }
    public Modopago(Integer idmodoPago, String descripcion, Integer cuotas, Double interes, Set facturas) {
       this.idmodoPago = idmodoPago;
       this.descripcion = descripcion;
       this.cuotas = cuotas;
       this.interes = interes;
       this.facturas = facturas;
    }
   
    public Integer getIdmodoPago() {
        return this.idmodoPago;
    }
    
    public void setIdmodoPago(Integer idmodoPago) {
        this.idmodoPago = idmodoPago;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getCuotas() {
        return this.cuotas;
    }
    
    public void setCuotas(Integer cuotas) {
        this.cuotas = cuotas;
    }
    public Double getInteres() {
        return this.interes;
    }
    
    public void setInteres(Double interes) {
        this.interes = interes;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
        @Override
    public boolean equals(Object other){
        return (other instanceof Modopago) && (idmodoPago != null)? idmodoPago.equals(((Modopago)other).idmodoPago):(other == this);
    }
    @Override
    public int hashCode(){
        return (idmodoPago != null)? (this.getClass().hashCode() + idmodoPago.hashCode()):super.hashCode();
    }
    @Override
    public String toString(){
        return String.format("Modopago: [%s]", descripcion);
    }
    
}


